version: '2'

services:
  db:
      image: postgres:alpine
      environment:
        POSTGRES_PASSWORD: postgres
  web:
    image: elixir:1.11.4-alpine
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "6379:6379"
      - "4000:4000"
    depends_on:
      - db

