#!/usr/bin/ruby
num_of_servers = ARGV[0].to_i
num_of_servers.times do |i|
  port = 6379 + i*1000
  pidfile = "/usr/local/var/run/redis_#{i}.pid"
  dbfilename = "dump_#{i}.rdb"
  conf_file = "redis_#{i}.conf"
  file_contents = "pidfile #{pidfile}\r\nport #{port}\r\ndbfilename #{dbfilename}\r\ninclude redis-defaults.conf"
  system("echo '#{file_contents}' > #{conf_file}")
  system("redis-server #{conf_file}")
end
